language: php

php:
    - 7.2
    
matrix:
  fast_finish: true

install: composer update --prefer-dist --dev --no-interaction $COMPOSER_FLAGS

script: vendor/bin/phpunit --coverage-text --whitelist src tests/

notifications:
    discord:
        channels:
          - 312160566291971:V7pRJV-3rzpjDuYxKIlbQ7Eihfg4PlIUShhesTdyg4IlRK0G7Akr_jm7SjzK-oqgFc6N
        pull_request_template:
          - 'Build [#%{build_number}](%{build_url}) ([%{commit}](%{compare_url})) of %{repository}@%{branch} in PR [#%{pull_request_number}](%{pull_request_url}) by %{author} %{result} in %{duration}'
        branch_template:
          - 'Build [#%{build_number}](%{build_url}) ([%{commit}](%{compare_url})) of %{repository}@%{branch} by %{author} %{result} in %{duration}'
    slack: redori:zPaW8aAbTCF9NJh13BtWq9UV
    email:
        - smeagolworms4@gmail.com
