services:
    _defaults:
        autowire: true
        public: false

    GollumSF\RestBundle\EventSubscriber\SerializerSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    GollumSF\RestBundle\EventSubscriber\ExceptionSubscriber:
        arguments:
            $debug: '%kernel.debug%'
        tags:
            - { name: kernel.event_subscriber }

    GollumSF\RestBundle\Serializer\Normalizer\:
        resource: '../../Serializer/Normalizer/*'
        public: false
        tags: [ 'serializer.normalizer' ]

    GollumSF\RestBundle\Serializer\Normalizer\DoctrineObjectDenormalizer:
        tags: [ 'serializer.normalizer' ]
        arguments:
            - '@GollumSF\RestBundle\Serializer\Normalizer\RecursiveObjectNormalizer'

    GollumSF\RestBundle\Search\ApiSearchInterface:
        class: GollumSF\RestBundle\Search\ApiSearch

    GollumSF\RestBundle\Metadata\Serialize\MetadataSerializeManagerInterface:
        class: GollumSF\RestBundle\Metadata\Serialize\MetadataSerializeManager

    GollumSF\RestBundle\Metadata\Serialize\Handler\AttributeHandler:
        tags:
            - { name: !php/const 'GollumSF\RestBundle\Metadata\Serialize\MetadataSerializeManagerInterface::HANDLER_TAG' }

    GollumSF\RestBundle\Metadata\Unserialize\MetadataUnserializeManagerInterface:
        class: GollumSF\RestBundle\Metadata\Unserialize\MetadataUnserializeManager

    GollumSF\RestBundle\Metadata\Unserialize\Handler\AttributeHandler:
        tags:
            - { name: !php/const 'GollumSF\RestBundle\Metadata\Unserialize\MetadataUnserializeManagerInterface::HANDLER_TAG' }

    GollumSF\RestBundle\Metadata\Validate\MetadataValidateManagerInterface:
        class: GollumSF\RestBundle\Metadata\Validate\MetadataValidateManager

    GollumSF\RestBundle\Metadata\Validate\Handler\AttributeHandler:
        tags:
            - { name: !php/const 'GollumSF\RestBundle\Metadata\Validate\MetadataValidateManagerInterface::HANDLER_TAG' }

    GollumSF\RestBundle\Request\ValueResolver\:
        resource: '../../Request/ValueResolver/*'
        tags:
            - { name: controller.argument_value_resolver, priority: 120 }
